# Site settings
title: HOPE Leadership Academy
description: >
  The purpose of HOPE Leadership Academy is to identify students who have leadership potential, 
  provide leadership and mentoring training through our three year, service oriented program, 
  and furnish program graduates as peer mentors to students in poverty.  Our goal is to decrease 
  the dropout rate and thus improve the quality of life in our schools, communities, and state.
baseurl: "/HOPE" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
link: http://hopeleadershipacademy.org
image: "{{ site.baseurl }}/assets/img/HOPE_logo.svg"

# Build settings
markdown: kramdown

exclude: ['node_modules','package.json','gruntfile.js']